__title__ = 'readwrite'
__description__ = 'readwrite - Quickly read/write file in common formats'
__version__ = '0.3.2'
__author__ = 'Enzo CACERES'
__author_email__ = 'enzo.caceres@crunchdao.com'
__url__ = 'https://github.com/crunchdao/readwrite'
